---
- hosts: all
  user: ubuntu
  gather_facts: False
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- hosts: all
  user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  vars:
    domain: www.yourdomain.com
    email: webmaster@yourdomain.com

  tasks:
  - name: copy source list files
    copy:
      src: "{{ item }}"
      dest: /etc/apt/sources.list.d/
      owner: root
      mode: 0600
    with_fileglob:
      - files/sources.list.d/*

  - name: add nginx gpg key
    apt_key:
      url: "https://nginx.org/keys/nginx_signing.key"
      state: present

  - name: update packages
    apt:
      update_cache: yes

  - name: install nginx
    apt:
      name: nginx
      state: latest

  - name: install letsencrypt
    apt:
      name: letsencrypt
      state: latest

  - name: create app www folder
    file:
      path: /var/www/
      mode: 0750
      owner: ubuntu
      group: nginx
      state: directory

  - name: create nginx snippets folder
    file:
      path: /etc/nginx/snippets
      mode: 0750
      state: directory

  - name: create letsencrypt www folder
    file:
      mode: 0750
      group: nginx
      path: /var/www/letsencrypt
      state: directory

  - name: copy nginx.conf
    copy:
      src: files/nginx/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: nginx
      mode: 0640
    notify:
      - restart nginx

  - name: copy nginx snippets
    template:
      src: "{{ item }}"
      dest: /etc/nginx/snippets/{{ item | basename | regex_replace('\.j2','') }}
      owner: root
      group: nginx
      mode: 0640
    with_fileglob:
      - files/nginx/snippets/*.j2
    notify:
      - restart nginx

  - name: copy nginx 'vhost' configs
    template:
      src: "{{ item }}"
      dest: /etc/nginx/conf.d/{{ item | basename | regex_replace('\.j2','') }}
      owner: root
      group: nginx
      mode: 0640
      validate: bash -c 'nginx -t -c /dev/stdin <<< "events { worker_connections 1; } http { include /etc/nginx/proxy_params; include %s; }"'
    with_fileglob:
      - files/nginx/conf.d/*.j2
    notify:
      - restart nginx

  - name: delete nginx default config
    file:
      path: /etc/nginx/conf.d/default
      state: absent

  - name: generate a safe dh prime
    command: openssl dhparam 2048 -out /etc/ssl/dh2048.pem
    args:
      creates: /etc/ssl/dh2048.pem
    notify:
      - restart nginx

  - name: enable and start nginx service
    service:
      name: nginx
      state: started
      enabled: yes

  - name: obtain ssl certificate via letsencrypt
    command: letsencrypt certonly --agree-tos -m {{ email }} --webroot --webroot-path /var/www/letsencrypt -d {{ domain }}
    args:
      creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
    notify:
      - restart nginx

  - name: Creates weekly cert renew check cronjob
    cron:
      minute: "20"
      hour: "5"
      weekday: "sun"
      name: "renew certificates"
      cron_file: "letsencrypt-RenewCert"
      user: "root"
      job: "letsencrypt renew && systemctl reload nginx"


  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: reloaded
